### PR TITLE
feat: add e2e tests

### PR DESCRIPTION
**Pull request by Pierre-RA**
Add necessary scaffolding for e2e tests.
Really, Angular2 and angular-cli make it simpler!

### CODE REVIEW

**Comment by Adrion** [comment]
It's not really a fix. It uses Chrome and not selenium. 
Do you have missed to --save a package ? 

```[09:39:30] E/launcher - Error: Error: Server terminated early with status 1
    at Error (native)
    at earlyTermination.catch.e (/Users/adrion/Documents/developpement/hon/Kconnect-search/node_modules/selenium-webdriver/remote/index.js:252:52)
    at process._tickCallback (internal/process/next_tick.js:103:7)```

/usr/bin/java is JAVA7

**Comment by Pierre-RA** [comment]
I've clone the repo on my personal computer and done `npm install && npm test`.
Everything is working fine for me.

**Comment by Adrion** [comment]
`java -version` output ?

**Comment by Pierre-RA** [comment]
`java version "1.8.0_77"`

**Pull request merged**
