### PR TITLE
fix: fathead has a better behavior

### PR DESCRIPTION
**Pull request by Pierre-RA**
Fathead has no longer height restrictions.
On mobile, if the text is too big, it becomes hidden until `show definitions` is clicked.

### CODE REVIEW

**Comment by Pierre-RA** [comment]
Fix #93

**Comment by Adrion** [comment]
capture d ecran 2017-04-05 a 13 56 42

When you "hide definition" in mobile and resize to sm size content stay hidden

I tried to restart tests and failed again

**Comment by Pierre-RA** [comment]
I kept the definition button. The definition stay visible when the width is bigger than 768px.

**Review by Adrion — CHANGES_REQUESTED** [review]
If you load page with size < 768px definition is shown by default & there's no hide/show switch btn.

Also, show all by default on desktop will not work with treatment fathead (see https://github.com/healthonnet/Kconnect-search/tree/feat-treatments WORK IN PROGRESS) that is way too long to be shown entirely by default.

**Review by Adrion — APPROVED** [review]

**Pull request merged**
